### PR TITLE
add linksTo and relationsTo

### PR DESCRIPTION
**Pull request by pfraze**
Add two funcs to enumerate links, or link-relations, between two messages.

Here's an example usage:

```js
function isaReplyTo (a, b) {
  var rels = mlib.relationsTo(a, b)
  return rels.indexOf('root') >= 0 || rels.indexOf('branch') >= 0
}
```

### CODE REVIEW

**Comment by pfraze** [comment]
RFR @dominictarr

**Comment by pfraze** [comment]
suggest bump minor

**Comment by dominictarr** [comment]
:+1: looks good.

**Comment by pfraze** [comment]
published `5.2.0`

**Pull request merged**
