### PR TITLE
relax isHash

### PR DESCRIPTION
**Pull request by dominictarr**
relaxes isHash to accept other values than `blake2s`

### CODE REVIEW

**Comment by pfraze** [comment]
What other hash algorithms are we using?

**Comment by pfraze** [comment]
Is this a hack to deal with feed IDs that arent hashes anymore?

**Comment by dominictarr** [comment]
yeah, this was just simpler than explicitly checking for ed25519.
We are actually still using a js implemention of blake2s.
we should probably switch to a C one... or sha256...

sodium does have blake but I'll have to update the binding

**Comment by pfraze** [comment]
How bad would it be to make an `isFeedId()` and update all the other code?

**Comment by dominictarr** [comment]
@pfraze we could do that... but I think this is good enough

**Pull request merged**
